---
date: 2023-10-17
title: Causal machine learning for estimating interventional effects mapped to a target trial
venue: VIC, Australia
---

Australasian Epidemiological Association 2023 Annual Scientific Meeting


# Abstract

Cohort studies frequently collect biological specimens like blood, urine, and faeces to obtain high-dimensional 'omics' data and other biomarker information. These data may be key to understanding the biological pathways mediating the effects of exposures on disease risk. The recent interventional effect approach for mediation analysis offers a promising avenue to address these problems. However, current implementations of this approach rely on parametric methods that may not be valid for these high-dimensional problems in which there can be many variables (multiple biomarkers) and complex relationships but a small sample size. We employed the efficient influence function within a nonparametric model to describe doubly robust estimators for interventional effects from which we developed targeted minimum loss-based and double machine learning estimators. The nuisance parameters of these estimators can be modelled using machine learning to tackle high-dimensional problems, with the use of sample splitting (i.e. discovery and validation sets) enabling valid inference. We examined the performance of these methods in simulation studies and applied them to investigate the longitudinal relationship between body mass index (BMI) and blood pressure (BP) in the Longitudinal Study of Australian Children, with potential mediation by the NMR metabolomic profile (228 metabolites). The proposed methods enable estimation of the indirect effect of an exposure on an outcome through a joint set of high-dimensional mediators in observational studies.



